### PR TITLE
Added stepper motor modules

### PR DESCRIPTION
**Pull request by khoipkv**
This commit brought in:
- Hardware+UI: ported from old qudi with modification to import dir path
- Logic: ported from old qudi with modification to import dir path and safe threading
- config file: added the stepper motor modules

### CODE REVIEW

**Comment by ttntinn** [comment]
Need to prove that it works on machine before merging!

**Comment by khoipkv** [comment]
image

Proved that it works.

**Comment by ttntinn** [comment]
@trezitorul This is an example of how we should merge a branch with approved review

**Review by ttntinn — APPROVED** [review]
LGTM

**Pull request merged**
